<?php

return [
    'USD' => ['name' => 'United States Dollar', 'symbol' => '$'],
    'EUR' => ['name' => 'Euro', 'symbol' => '€'],
    'IDR' => ['name' => 'Indonesian Rupiah', 'symbol' => 'Rp'],
    'JPY' => ['name' => 'Japanese Yen', 'symbol' => '¥'],
    'GBP' => ['name' => 'British Pound Sterling', 'symbol' => '£'],
    'AUD' => ['name' => 'Australian Dollar', 'symbol' => 'A$'],
    'CAD' => ['name' => 'Canadian Dollar', 'symbol' => 'C$'],
    'CHF' => ['name' => 'Swiss Franc', 'symbol' => 'CHF'],
    'CNY' => ['name' => 'Chinese Yuan', 'symbol' => '¥'],
    'SEK' => ['name' => 'Swedish Krona', 'symbol' => 'kr'],
    'NZD' => ['name' => 'New Zealand Dollar', 'symbol' => 'NZ$'],
    'MXN' => ['name' => 'Mexican Peso', 'symbol' => '$'],
    'SGD' => ['name' => 'Singapore Dollar', 'symbol' => 'S$'],
    'HKD' => ['name' => 'Hong Kong Dollar', 'symbol' => 'HK$'],
    'NOK' => ['name' => 'Norwegian Krone', 'symbol' => 'kr'],
    'KRW' => ['name' => 'South Korean Won', 'symbol' => '₩'],
    'TRY' => ['name' => 'Turkish Lira', 'symbol' => '₺'],
    'RUB' => ['name' => 'Russian Ruble', 'symbol' => '₽'],
    'INR' => ['name' => 'Indian Rupee', 'symbol' => '₹'],
    'BRL' => ['name' => 'Brazilian Real', 'symbol' => 'R$'],
    'ZAR' => ['name' => 'South African Rand', 'symbol' => 'R'],
    'MYR' => ['name' => 'Malaysian Ringgit', 'symbol' => 'RM'],
    'THB' => ['name' => 'Thai Baht', 'symbol' => '฿'],
    'PHP' => ['name' => 'Philippine Peso', 'symbol' => '₱'],
    'VND' => ['name' => 'Vietnamese Dong', 'symbol' => '₫'],
];
